* <<<602>>> SOFTWARE SYSTEM SECURITY
:properties:
:author: Dr. V. Balasubramanian and Dr. J. Bhuvana
:date: 12-04-2021
:end:

#+startup: showall
{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
New Syllabus

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |  0  |   0 |    0 |    0 |    0 |    2 |    0 |    1 |
| CO2            | K2 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |  0  |   0 |    0 |    0 |    0 |    2 |    0 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |  0  |   0 |    0 |    0 |    0 |    2 |    0 |    1 |
| CO4            | K3 |   1 |   1 |   0 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    0 |    0 |    0 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    2 |    0 |    1 |

** COURSE OBJECTIVES
- To study about the essentials of computer security
- To acquire knowledge on encryption Techniques
- To understand authentication applications
- To learn various access control mechanisms
- To understand different security policies

{{{unit}}}         
| UNIT I | OVERVIEW OF SECURITY AND  ENCRYPTION TECHNIQUES | 9 |
Computer Security Concepts --  Security Architecture -- Attacks, Services and Mechanisms -- Fundamental Security Design
Principles -- Attack Surfaces and Attack Trees -- Algebraic structures – Modular arithmetic-Euclid‟s algorithm- 
Congruence and matrices -Groups, Rings, Fields- Finite fieldsBlock Cipher -- Data Encryption Standard -- Advanced Encryption Standard 
-- Stream Ciphers and RC4 -- Cipher Block Modes of Operation 
 
{{{unit}}}      
| UNIT II | PUBLIC KEY CRYPTOGRAPHY | 9 |
Primes –- Primality Testing –Factorization –- Euler‘s totient function, Fermat‘s and Euler‘s Theorem –- Chinese Remainder Theorem – 
Exponentiation and logarithm –- Public-Key Cryptography and Message Authentication: Secure Hash Functions -- HMAC -- RSA -- Diffie-Hellman -- 
Elliptic curve arithmetic -- Elliptic curve cryptography


{{{unit}}}      
| UNIT III | Network Protocols | 9 |
User Authentication: Authentication applications – Kerberos -- X.509 -- Malicious Software -- Types -- Threat 
-- Propagation -- Payload -- Countermeasue -- Intruder Detection -- Firewall -- Types -- Access Policy
{{{unit}}}      
| UNIT III | SOFTWARE SECURITY AND CLOUD SECURITY | 9 |
Software Security: Software Security Issues -- Handling Program Input
-- Writing Safe Program Code -- Interacting with the Operating System
and Other Programs -- Handling Program Output; Operating System
Security : Introduction to Operating System Security -- System
Security Planning -- Operating Systems Hardening -- Application
Security -- Security Maintenance -- Linux/Unix Security -- Windows
Security -- Virtualization Security; Cloud and IoT security: Cloud
Computing -- Cloud Security Concepts -- Cloud Security Approaches --
The Internet of Things -- IoT Security

{{{unit}}}
| UNIT IV | Security Practice | 9 |
Cloud and IoT security: Cloud Computing -- Cloud Security Concepts -- Cloud Security Approaches; Transport Layer Security: TLS -- HTTPS -- SSH;
Electronic Mail security: PGP, S/MIME – IP security – Web Security; IP Security: IPSec
{{{unit}}}
| UNIT IV | ACCESS CONTROL MATRIX | 8 |
 Access Control Matrix: Protection State-- Access Control Matrix Model
-- Protection State Transitions -- Copying, Owning, and the
Attenuation of Privilege; Security Policies: The Nature of Security
Policies -- Types of Security Policies -- The Role of Trust -- Types
of Access Control -- Policy Languages -- Example: Academic Computer
Security Policy -- Security and Precision

{{{unit}}}
| UNIT V |  SECURITY POLICIES             | 8 |
The Nature of Security Policies -- Types of Security Policies -- The
Role of Trust; Confidentiality policy:The Bell-LaPadula Model;
Integrity policy: Clark-Wilson Integrity Model; Availability policy:
Denial of Service Models; Hybrid policy: Chinese Wall Model.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Examine symmetric and asymmetric ciphers (K3)
- Examine the different authentication schemes (K3)
- Outline the security mechanisms adapted in OS, Cloud and IoT  (K2)
- Explain the functionality of access control mechanism (K2)
- Compare and contrast various security policies (K3)

** TEXT BOOKS

1. William Stallings, Lawrie Brown, ``Computer Security  Principles and Practice'', Seventh Edition, Pearson, 2019.
2. William Stallings, "Network Security Essentials: Applications and Standards", Sixth edition, Pearson, 2017 
2. Matt Bishop, ``Computer Security: Art and Science'', Second edition, Addison Wesley, 2019 (Unit IV, V).


** REFERENCES
1. Salomon, David , ``Data Privacy and Security'', Springer
2. Dorothy Elizabeth Rob, ling Denning , ``Cryptography and data Security'',   ADDISON-WESLEY PUBLISHING COMPANY, 2003 
3. Houbing Song , Glenn A. Fink , Sabina Jeschke ,  ``Security and Privacy in Cyber-Physical Systems: Foundations, Principles, and Applications'',  Wiley-IEEE Press, November 2017 
4. Charlie Kaufman, Radia Perlman and Mike Speciner , ``Network Security: Private Communication in a Public World'', Second  Edition, Pearson Education, 2017.
5. Wenliang Du, ``Computer Security: A Hands-on Approach'', CreateSpace Independent Publishing Platform, First Edition, 2017.
6. William Stallings, ``Network Security Essentials: Applications and    Standards'', Sixth Edition, Pearson, 2017.
7. Mauricio Arregoces, Maurizio Portolani, ``Data Center    Fundamentals'', Cisco Press, 2003.

    
 




