* <<<PE102>>> ADVANCED DATABASE MANAGEMENT SYSTEMS
:properties:
:author: Mr.B.Senthil Kumar and Dr. P. Mirunalini
:date: 30-03-2021
:end:

** R2021 CHANGES :noexport:
1. Unit 4 is fully changed to Intelligent databases.
2. Unit 5 is fully changed to Mobile and Spatial databases.
3. NoSQL databases covered in DBMS core course (R2017-Unit4).
4. Big data - a separate course is introduced (R2017-Unit 5).


#+startup: showall
{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO2            | K2 |   2 |   2 |   1 |   1 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| Score          |    |  14 |  10 |   9 |   9 |   5 |   0 |   0 |   5 |   5 |    5 |    0 |    5 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |

#+begin_comment
1. One professional elective was offered by AU-2017 "Advanced Topics on Databases".
2.No changes in the first and second units.The last unit of AU-2017 was puhed to 3rd unit.
The 4th and 5th units are new units.
3.Syllabus is different from M.E syllabus
4.Five course outcomes are specified and alligned with units.
5.Not Applicable.
#+end_comment

** COURSE OBJECTIVES
The student should be able to:
- To acquire knowledge on parallel and distributed databases and their applications 
- To study the usage and applications of Object and Object Relational Databases
- To learn about XML Database
- To acquire knowledge in intelligent Databases
- To learn the concepts of emerging technologies

{{{unit}}}
|UNIT I |PARALLEL AND DISTRIBUTED DATABASES| 9 |
Database System Architectures: Centralized and client-server
architectures -- Server system architectures -- Parallel systems --
Distributed systems; Parallel Databases: I/O parallelism -- Inter and
intra query parallelism -- Inter and intra operation parallelism --
Design of parallel systems -- Distributed database concepts --
Distributed data storage -- Distributed transactions -- Commit
protocols -- Concurrency control -- Distributed query processing --
Case studies.

{{{unit}}}
|UNIT II | OBJECT AND OBJECT RELATIONAL DATABASES | 9 |
Concepts for Object Databases: Object identity -- Object structure --
Type constructors -- Encapsulation of operations -- Methods --
Persistence -- Type and class hierarchies -- Inheritance -- Complex
Objects -- Object database standards; Languages and Design: ODMG model
-- ODL -- OQL -- Object relational and extended; Relational Systems:
Object relational features in SQL/Oracle -- Case studies.

{{{unit}}}
|UNIT III | XML DATABASES | 9 |
XML Databases: XML-Data model -- DTD -- XMLSchema -- XML Query
Languages -- Storing XML in databases -- XML and SQL -- Native XML
databases -- Web databases.

{{{unit}}}
|UNIT IV | INTELLIGENT DATABASES | 9 |
Active  Databases:Syntax and Semantics(Oracle,DB2) -- Taxonomy -- 
Applications -- Design Principles for Active Rules; Deductive 
Databases: Logic of Query Languages -- Datalog -- Recursive Rules 
-- Syntax and Semantics of Datalog Languages -- Implementation 
of Rules and Recursion -- Recursive Queries in SQL.

#+begin_comment
Newly added to meet industry requirements
#+end_comment

{{{unit}}}
|UNIT V | EMERGING TECHNOLOGIES | 9 |
Mobile Databases: Location and Handoff Management -- Effect of 
Mobility on Data Management -- Location  Dependent Data Distribution 
-- Mobile Transaction Models -- Concurrency Control -- Transaction 
Commit Protocols; Spatial  Databases: Spatial Data Types -- Spatial 
Relationships -- Spatial Data Structures -- Spatial Access Methods 
-- Spatial DB Implementation; Geographic Information Systems.
 

#+begin_comment
Newly added to meet industry requirements
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Learn Parallel and Distributed Databases (K2)
- Design and query in Object and Object Relational Databases (K3)
- Design schema and query XML Databases (K3)
- Apply rules to infer knowledge from databases. (K3)
- Learn concepts in mobile and spatial databases (K2).

** TEXT BOOKS 
1. Elmasri, Ramez, Shamkant Navathe, ``Fundamentals of database
   systems'', 7th Edition, Pearson, 2016 
2. Thomas Cannolly and Carolyn Begg, “Database  Systems,  
   A Practical Approach to Design, Implementation and Management”, 
   Third Edition, Pearson Education, 2007.

** REFERENCES
1. Capriolo, Edward, Dean Wampler, Jason Rutherglen. ``Programming
   Hive: Data Warehouse and Query Language for Hadoop'', O'Reilly
   Media Inc, 2012.
2. Henry F Korth, Abraham Silberschatz, S Sudharshan, ``Database
   System Concepts'', 6th Edition, McGraw Hill, 2011.
3. Carlo Zaniolo, Stefano Ceri, Christos Faloutsos, Richard T
   Snodgrass, V S Subrahmanian, Roberto Zicari, ``Advanced Database
   Systems'', Morgan Kaufmann publishers, 2006
4. Membrey, Peter, Eelco Plugge, DUPTim Hawkins. ``The Definitive
   Guide to MongoDB: The NoSQL Database for Cloud and Desktop
   Computing'', Apress, 2011.


