* <<<PE506>>> MOBILE COMPUTING
:properties:
:author: Dr. V. S. Felix Enigo and Dr. A. Beulah
:date: 29/03/2021
:end:

#+startup: showall
{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** CO-PO MAPPING                                                   :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    0 |    0 |    0 |
| CO2            | K3 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    0 |    0 |    0 |
| CO3            | K3 |   2 |   3 |   0 |   0 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    0 |    0 |    0 |
| CO4            | K2 |   1 |   3 |   0 |   0 |   3 |   0 |   0 |   0 |   0 |    0 |    0 |    0 |    1 |    0 |    0 |
| CO5            | K3 |   1 |   3 |   1 |   2 |   2 |   0 |   0 |   0 |   0 |    1 |    0 |    0 |    2 |    0 |    0 |
| CO6            | K3 |   3 |   3 |   3 |   3 |   2 |   1 |   0 |   0 |   1 |    2 |    0 |    0 |    2 |    3 |    1 |
| Score          |    |  11 |  18 |   4 |   5 |   7 |   1 |   0 |   0 |   1 |    3 |    0 |    0 |    6 |    3 |    1 |
| Course Mapping |    |   2 |   3 |   1 |   1 |   1 |   1 |   0 |   0 |   1 |    1 |    0 |    0 |    1 |    1 |    1 |


** R2021 CHANGES :noexport:
1. Unit 1 no change
2. Unit 2 network and transport layer combined, removed VANET, WAP (outdated)
3. Unit 3 2G reduced to overview, 3G as it is, 4G included (latest)
4. Unit 5 in old syllabus is expanded to Unit - IV and Unit- V 
5. Unit 4 and Unit 5 includes mobile application development

** COURSE OBJECTIVES
The student should be made to:
- Understand the basic concepts of mobile computing
- Know the functionalities of layers in protocol stack
- Learn the basics of mobile telecommunication system
- Build and deploy mobile applications in mobile platforms
- Develop full fledged mobile applications

{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Introduction to Mobile Computing; Media Access Control (MAC):
Motivation for a specialized MAC-- SDMA -- FDMA -- TDMA -- CDMA --
Comparison of S/T/F/CDMA; Wireless LAN: Infrastructure based and adhoc
networks -- IEEE 802.11 -- Bluetooth.

{{{unit}}}
|UNIT II | NETWORK AND TRANSPORT LAYER | 9 |
Mobile IP: Goals, assumptions and requirements -- Entities and
terminology -- IP packet delivery -- Agent discovery -- Registration
--Tunneling and encapsulation -- Optimizations; DHCP; AdHoc: Routing
-- Proactive routing protocol-DSDV -- Reactive routing protocol - DSR, 
AODV -- Hybrid routing –ZRP; Traditional TCP – Classical TCP improvements.


{{{unit}}}
|UNIT III | MOBILE TELECOMMUNICATION SYSTEMS | 9 |
Introduction; GSM Overview; 3GPP; UMTS  and  IMT-2000: Architecture --  User  Equipment --  RNS --  UTRAN -- Node B -- RNC Functions -- IP Multimedia Subsystem; 4G Cellular Network: LTE Network Architecture -- EPS Interfaces -- EPS Protocols and Planes -- LTE Protocol Strack -- SDU and PDU -- RRC -- PDCP -- RLC -- MAC -- PHY.

{{{unit}}}
|UNIT IV | SETTING UP AND DEPLOYMENT OF MOBILE APPLICATIONS | 8 |
iOS: iOS Architecture Layers -- iOS Simulator; Android: Introduction to Android -- Android's Development Environment: Introducing the Android SDK -- Exploring the development environment -- Building an Android application -- Using the Android emulator - Developing simple applications using mobile platforms.

{{{unit}}}
|UNIT V | APPLICATION DEVELOPMENT FOR MOBILE OS| 10 |
User Interfaces -- Intents and services -- Storing and Retrieving data -- Notifications and alarms -- Location --  Putting Android to work in a field service application.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
- Explain the functionalities of MAC protocols in wireless networks (K2)
- Choose appropriate algorithms for routing and transporting data for a given scenario (K3)
- Demonstrate the concepts of 3G and 4G Cellular Networks (K2)
- Make use of various mobile platforms to develop and deploy mobile applications (K3)
- Develop mobile applications using various features learnt (K3)
- Develop mobile App for Solving a real world problems in teams by choosing appropriate mobile components and applying best practices in coding  with a clear documentation of procedure and approach (K4)

** TEXT BOOKS
1. Jochen H Schller, ``Mobile Communications'', Pearson Education, New
   Delhi, 2nd Edition, 2007 (Unit I--III).
2. Ableson, W.F., Sen, R. and King, C., 2011. ``Android in Action Second Edition'', Manning Publications Co.(Unit IV,V)

** REFERENCES
1. ElNashar, A., El-Saidny, M.A. and Sherif, M., 2014. ``Design, deployment and performance of 4G-LTE networks: A practical approach'', John Wiley & Sons.(4G)
2. Helal, Sumi, Raja Bose, and Wendong Li. ``Mobile platforms and development environments'', Synthesis Lectures on Mobile and Pervasive Computing, 2012.(iOS)
3. Helal, Abdelsalam A., et al. ``Any time, anywhere computing: Mobile computing concepts and technology'', Vol. 522. Springer Science & Business Media, 1999.
4. Dharma Prakash Agarval, Qing and An Zeng, ``Introduction to Wireless and Mobile systems'', Thomson Asia Pvt Ltd, 2005.	
5. C.K.Toh, ``AdHoc Mobile Wireless Networks'', First Edition, Pearson Education, 2002.





